# Generated by Django 4.1 on 2023-09-04 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IfcModel',
            fields=[
                ('id', models.BinaryField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BinaryField(max_length=16, primary_key=True, serialize=False)),
                ('parent_model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.ifcmodel')),
            ],
        ),
    ]
