# Generated by Django 4.1 on 2023-09-04 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='parent_model_id',
            new_name='parent_model',
        ),
    ]
