# Generated by Django 4.1 on 2023-09-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_rename_parent_model_id_annotation_parent_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ifcmodel',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
