# Generated by Django 4.1 on 2023-09-05 14:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_annotation_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ifcmodel',
            old_name='name',
            new_name='model_name',
        ),
        migrations.AddField(
            model_name='ifcmodel',
            name='owner_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annotation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ifcmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
