# Generated by Django 4.1 on 2023-09-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_annotation_express_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifcmodel',
            name='display_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
