# Generated by Django 4.1 on 2023-09-09 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_organisation_url_name'),
        ('viewer', '0007_ifcmodel_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifcmodel',
            name='owner_organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.organisation'),
        ),
    ]
