# Generated by Django 4.1 on 2023-09-09 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_ifcmodel_owner_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ifcmodel',
            name='owner_name',
        ),
    ]
