# Generated by Django 4.1 on 2023-09-09 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_organisation_url_name'),
        ('viewer', '0009_remove_ifcmodel_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
