# Generated by Django 4.1 on 2023-10-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_annotation_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='center_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='annotation',
            name='center_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='annotation',
            name='center_z',
            field=models.FloatField(default=0),
        ),
    ]
