# Generated by Django 4.1 on 2023-09-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='url_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
