# Generated by Django 4.1 on 2023-09-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_organisation_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='url_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
