# Generated by Django 4.1 on 2023-11-20 21:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IfcModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WallElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('express_id', models.IntegerField(default=-1)),
                ('parent_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhaw.ifcmodel')),
            ],
        ),
    ]
