# Generated by Django 4.1 on 2023-11-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhaw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifcmodel',
            name='author_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ifcmodel',
            name='project_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
